In [2]:
import os, nltk, glob
import pandas as pd
from docx import Document

In [52]:
#import os

def readFile(fileName):
        '''
        Read a file given its name as a string.
        Modules required: os
        UNIX packages required: antiword, ps2ascii
        '''
        extension = fileName.split(".")[-1]
        
        if extension == "docx":
            try:
                document = Document(fileName)
                output = "\n".join([pgraph.text for pgraph in document.paragraphs])
                return output, extension
            except:
                print('####### WARNING ####### WARNING ####### WARNING #######')
                print(fileName+' ========> IS EMPTY ')
                print('####### WARNING ####### WARNING ####### WARNING #######')
                return 'NO_DATA', extension
                pass
        
        elif extension == "pdf":
            # ps2ascii converst pdf to ascii text
            # May have a potential formatting loss for unicode characters
            # return os.system(("ps2ascii %s") (fileName))
            try:
                
                return convertPDFToText(fileName), extension
            
            except:
                return ''
                pass
        else:
            print('Unsupported format')
            return '', ''

In [3]:
!pwd

/c/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/src/draft_scripts

In [97]:
#os.chdir("/Users/Robert_Mac/Documents/GitHub/Labs/Block_7/Glentel/resumes")

In [120]:
#!pwd

In [54]:
resume_data, resume_type = readFile("../../data/resumes/Ahammed, Kawser - WW 284.docx")

In [55]:
resume_data

'Kawser Ahammed\n414-1225 Moss Avenue, Saskatoon, SK, S7H5B1           Cell: (306) 881-1571, Email: kawser.dc@gmail.com\n\nHIGHLIGHTS OF QUALIFICATIONS\n2+ years experience in Direct Sales and Customer service\nCertificate of service best customer service (Saskatchewan Tourism Education Council)\nProficient in using Microsoft Office\nMultilingual: English, Hindi, Urdu and Bangla\n\nSKILLS AND EXPERIENCE\nSales & Customer Service Skills:\nUnderstanding customer needs and suggesting solutions\nAbility to work one-on-one with patients and determine individual needs\nReading customer minds and directs them to a long-term profitable transaction\nStrong Customer Service oriented\n\nSupporting Skills:\nRespond well to new challenges and opportunities to learn\nDetail oriented and works with a high degree of accuracy\nProfound ability to multitask in a fast-paced environment\nExceptional interpersonal and organizational skills\nGood sense of time management\n………………………………………………………………………………………………………………………………………………………………….\nEXEPERIENCE SYNOPSIS\nBookkeeper, 786 Accounting & Tax, Saskatoon, SK                                                          May 2019- Continuing\nConnected Solution Specialist, Bestbuy, Saskatoon, SK                                        October 2017- August 2018\nSales Associate, Old Navy, Saskatoon, SK                                                                  August 2017- January 2018\nStorefront Attendant, Tim Horton’s, Saskatoon, SK                                              September 2015- June 2016\nBusiness Officer, Square Hospitals Ltd, Dhaka, Bangladesh                                         March 2014- June 2015\nAdmin Officer, Community Medical College & Hospital, Dhaka, Bangladesh       May 2012- February 2014\n\nEDUCATION\nAccounting Certificate, Saskatchewan Polytechnic, Saskatoon, SK                                                               2019\nBachelor of Business Studies, National University, Bangladesh                                                                    2010\n\nREFERENCE \nArsalan Neshan, Sales Supervisor, Best Buy, Cell: 306-881-0536, Email: aneshan@bestbuycanada.ca\nPanna Dev, Operation Manager, Old Navy, Cell: 306-850-5392, Email: panna_rds14@yahoo.com'

In [101]:
# Show imported resume by line
resume_data.split("\n")

['Kawser Ahammed',
 '414-1225 Moss Avenue, Saskatoon, SK, S7H5B1           Cell: (306) 881-1571, Email: kawser.dc@gmail.com',
 '',
 'HIGHLIGHTS OF QUALIFICATIONS',
 '2+ years experience in Direct Sales and Customer service',
 'Certificate of service best customer service (Saskatchewan Tourism Education Council)',
 'Proficient in using Microsoft Office',
 'Multilingual: English, Hindi, Urdu and Bangla',
 '',
 'SKILLS AND EXPERIENCE',
 'Sales & Customer Service Skills:',
 'Understanding customer needs and suggesting solutions',
 'Ability to work one-on-one with patients and determine individual needs',
 'Reading customer minds and directs them to a long-term profitable transaction',
 'Strong Customer Service oriented',
 '',
 'Supporting Skills:',
 'Respond well to new challenges and opportunities to learn',
 'Detail oriented and works with a high degree of accuracy',
 'Profound ability to multitask in a fast-paced environment',
 'Exceptional interpersonal and organizational skills',
 'Good sense of time management',
 '………………………………………………………………………………………………………………………………………………………………….',
 'EXEPERIENCE SYNOPSIS',
 'Bookkeeper, 786 Accounting & Tax, Saskatoon, SK                                                          May 2019- Continuing',
 'Connected Solution Specialist, Bestbuy, Saskatoon, SK                                        October 2017- August 2018',
 'Sales Associate, Old Navy, Saskatoon, SK                                                                  August 2017- January 2018',
 'Storefront Attendant, Tim Horton’s, Saskatoon, SK                                              September 2015- June 2016',
 'Business Officer, Square Hospitals Ltd, Dhaka, Bangladesh                                         March 2014- June 2015',
 'Admin Officer, Community Medical College & Hospital, Dhaka, Bangladesh       May 2012- February 2014',
 '',
 'EDUCATION',
 'Accounting Certificate, Saskatchewan Polytechnic, Saskatoon, SK                                                               2019',
 'Bachelor of Business Studies, National University, Bangladesh                                                                    2010',
 '',
 'REFERENCE ',
 'Arsalan Neshan, Sales Supervisor, Best Buy, Cell: 306-881-0536, Email: aneshan@bestbuycanada.ca',
 'Panna Dev, Operation Manager, Old Navy, Cell: 306-850-5392, Email: panna_rds14@yahoo.com']

In [56]:
line1 = resume_data.split("\n")[1]
line1

'414-1225 Moss Avenue, Saskatoon, SK, S7H5B1           Cell: (306) 881-1571, Email: kawser.dc@gmail.com'

In [57]:
line1.split(",")

['414-1225 Moss Avenue',
 ' Saskatoon',
 ' SK',
 ' S7H5B1           Cell: (306) 881-1571',
 ' Email: kawser.dc@gmail.com']

In [58]:
line1.split()

['414-1225',
 'Moss',
 'Avenue,',
 'Saskatoon,',
 'SK,',
 'S7H5B1',
 'Cell:',
 '(306)',
 '881-1571,',
 'Email:',
 'kawser.dc@gmail.com']

In [37]:
from glob import glob
import re
import os
import win32com.client as win32
from win32com.client import constants

# Create list of paths to .doc files
# paths = glob('C:\\path\\to\\doc\\files\\**\\*.doc', recursive=True)
paths = glob('C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/*.doc', recursive=True)

def save_as_docx(path):
    # Opening MS Word
    word = win32.gencache.EnsureDispatch('Word.Application')
    
    doc = word.Documents.Open(path)
    doc.Activate ()

    # Rename path with .docx
    new_file_abs = os.path.abspath(path)
    new_file_abs = re.sub(r'\.\w+$', '.docx', new_file_abs)

    # Save and Close
    word.ActiveDocument.SaveAs(
        new_file_abs, FileFormat=constants.wdFormatXMLDocument
    )
    doc.Close(False)

for path in paths:
    save_as_docx(path)

com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Word', "Sorry, we couldn't find your file. Was it moved, renamed, or deleted?\r (C:\\//Users/NIX/Documents/Project/Gith...)", 'wdmain11.chm', 24654, -2146823114), None)

In [45]:
for i, doc in enumerate(glob("C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/*.doc")):
    print(doc)

TypeError: 'module' object is not callable

In [61]:
#!/usr/bin/env python

import glob
import win32com.client

word = win32com.client.Dispatch("Word.Application")
#word.visible = 0

for i, doc in enumerate(glob.glob("../../data/resumes/*.doc")):
#for i, doc in enumerate(glob.glob("C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/*.doc")):
    in_file = os.path.abspath(doc)
    wb = word.Documents.Open(in_file)
    out_file = os.path.abspath("out{}.docx".format(i))
    wb.SaveAs2(out_file, FileFormat=16) # file format for docx
    wb.Close()

word.Quit()

In [62]:
for i, doc in enumerate(glob.glob("../../data/resumes/*.doc")):
    print(doc)

../../data/resumes\Dahdeh, Marwen - WE 503.doc
../../data/resumes\Gendron-Poirier, William - WE 518.doc
../../data/resumes\Khan, Nabeel - WE 1076.doc
../../data/resumes\Krakana, Francis - WE 542.doc
../../data/resumes\Lachance, Stephanie - WE 521.doc
../../data/resumes\Rabbani, Bilal - TB 461.doc
../../data/resumes\Yang, Jimmy - WE 545.doc
../../data/resumes\Yang, Lijia - WW 253.doc
../../data/resumes\~$nmore, Will - TB 704.doc

In [69]:
file_dir = "../../data/resumes/"

for root, dirs, files in os.walk(file_dir):
    print(files)
    for file in files:
        #print(file)
        file_name = file.split(".")[0]
        #print(file_name)
        filepath = os.path.join(root, file)
        #print(filepath)

['Abbasi, Samiee Z - WW 374 - N42.docx', 'Dahdeh, Marwen - WE 503.doc', 'Gendron-Poirier, William - WE 518.doc', 'Khan, Nabeel - WE 1076.doc', 'Krakana, Francis - WE 542.doc', 'Lachance, Stephanie - WE 521.doc', 'Rabbani, Bilal - TB 461.doc', 'Yang, Jimmy - WE 545.doc', 'Yang, Lijia - WW 253.doc', '~$nmore, Will - TB 704.doc']

In [70]:
#!/usr/bin/env python

# Convert from doc to docx using word application
import win32com.client

word = win32com.client.Dispatch("Word.Application")
#word.visible = 0

file_dir = "../../data/resumes/"

file_convert_log = []

for root, dirs, files in os.walk(file_dir):
    for file in files:
        
        file_extension = file.split(".")[-1]
        
        if file_extension in ["docx", "rtf", "pdf", "txt"]: #Skip other file types
            skip=True
            continue
        elif file.startswith('~'): #Ignore hidden files
            skip=True
            continue
        else: 
            file_name = file.split(".")[0]
            #print(file_name)
            file_path_name = os.path.join(root, file_name)
            #print(file_path)
            in_file = os.path.abspath("{}.doc".format(file_path_name))
            out_file = os.path.abspath("{}.docx".format(file_path_name))
            print("processing file:", file)
        try:
            wb = word.Documents.Open(in_file)
            wb.SaveAs2(out_file, FileFormat=16) # file format for docx = 16
            file_convert_log.append(file)
        except TypeError:
            continue
            wb.Close()

word.Quit()

# Save convert log to txt file
file_path_name = os.path.join(root, 'doc_to_docx_log.txt')
f = open(file_path_name,'w')
f.write("Total of {} files converted\n".format(len(file_convert_log)))
for item in file_convert_log:
    f.write(item+'\n')
f.close() 
print('Done!')
print("\nSuccesfully converted {} files".format(len(file_convert_log)))
print("Files converted saved in `doc_to_docx_log.txt`.")

processing file: Dahdeh, Marwen - WE 503.doc
processing file: Gendron-Poirier, William - WE 518.doc
processing file: Hanmore, Will - TB 704.doc
processing file: Khan, Nabeel - WE 1076.doc
processing file: Krakana, Francis - WE 542.doc
processing file: Lachance, Stephanie - WE 521.doc
processing file: Rabbani, Bilal - TB 461.doc
processing file: Yang, Jimmy - WE 545.doc
processing file: Yang, Lijia - WW 253.doc
Done!

Succesfully converted 9 files
Files converted saved in `doc_to_docx_log.txt`.

In [69]:
#Move doc files to doc folder

## Read file into a list
file_dir = "../../data/resumes/"
file_path = os.path.join(file_dir, 'doc_to_docx_log.txt')

with open(file_path) as f:
    file_list = list(f)
file_list = list(map(lambda s: s.strip(), file_list))[1:] #remove "\n from text"

# Make doc_files directoty
folder_path = os.path.join(file_dir, 'doc_files')
try:
    os.mkdir(folder_path)
except Exception as e:
    print(e) 
    pass

# Move files
for item in file_list:
    source = os.path.join(file_dir, item)
    destination = os.path.join(folder_path+'/', item)
    os.rename(source, destination)
    record = str(item)+' moved into'+folder_path
    print(record)
print("Done!")

Dahdeh, Marwen - WE 503.doc moved into../../data/resumes/doc_files
Done!
Gendron-Poirier, William - WE 518.doc moved into../../data/resumes/doc_files
Done!
Hanmore, Will - TB 704.doc moved into../../data/resumes/doc_files
Done!
Khan, Nabeel - WE 1076.doc moved into../../data/resumes/doc_files
Done!
Krakana, Francis - WE 542.doc moved into../../data/resumes/doc_files
Done!
Lachance, Stephanie - WE 521.doc moved into../../data/resumes/doc_files
Done!
Rabbani, Bilal - TB 461.doc moved into../../data/resumes/doc_files
Done!
Yang, Jimmy - WE 545.doc moved into../../data/resumes/doc_files
Done!
Yang, Lijia - WW 253.doc moved into../../data/resumes/doc_files
Done!

In [48]:
for item in file_convert_log:
    source = os.path.join(root, item)
    #print(source)
    destination = os.path.join(folder_path+'/', item)
    #print(destination)
    os.rename(source, destination)
#     record = str(item)+' moved into'+folder_path
#     print(record)
# print('Done!')

In [35]:
for root, dirs, files in os.walk(file_dir):
    print(root)
    for file in files:
        print(file)

../../data/resumes/
Abbasi, Samiee Z - WW 374 - N42.docx
Almeida, Julian - WW 359 - N6R.rtf
Dahdeh, Marwen - WE 503.doc
Dahdeh, Marwen - WE 503.docx
doc_to_docx_log.txt
Gendron-Poirier, William - WE 518.doc
Gendron-Poirier, William - WE 518.docx
Gervais, Dominic - WE 1345 - N5J.pdf
Hanmore, Will - TB 704.doc
Hanmore, Will - TB 704.docx
Khan, Nabeel - WE 1076.doc
Khan, Nabeel - WE 1076.docx
Krakana, Francis - WE 542.doc
Krakana, Francis - WE 542.docx
Lachance, Stephanie - WE 521.doc
Lachance, Stephanie - WE 521.docx
Rabbani, Bilal - TB 461.doc
Rabbani, Bilal - TB 461.docx
Yang, Jimmy - WE 545.doc
Yang, Jimmy - WE 545.docx
Yang, Lijia - WW 253.doc
Yang, Lijia - WW 253.docx
~$nmore, Will - TB 704.doc

In [44]:
path = os.path.join(root, 'doc_files/'+'item')
path
# try:
#     os.mkdir(path)
# except Exception as e:
#     print(e) 
#     pass

'../../data/resumes/doc_files/item'

In [58]:
test = 'Dahdeh, Marwen - WE 503.doc'
test.split('.')[0]

'Dahdeh, Marwen - WE 503'

In [69]:
word = win32.gencache.EnsureDispatch('Word.Application')

In [32]:
import os.path

import win32com.client



baseDir = 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/' # Starting directory for directory walk



word = win32com.client.Dispatch("Word.Application")



for dir_path, dirs, files in os.walk(baseDir):

    for file_name in files:

        file_path = os.path.join(dir_path, file_name)

        file_name, file_extension = os.path.splitext(file_path)

        if file_extension.lower() == '.doc': # 

            docx_file = '{0}{1}'.format(file_path, 'x')

            if not os.path.isfile(docx_file): # Skip conversion where docx file already exists

                print('Converting: {0}'.format(file_path))

                #try:

                wordDoc = word.Documents.Open(file_path, False, False, False)

                wordDoc.SaveAs2(docx_file, FileFormat = 16)

                wordDoc.Close()

                #except Exception: 

                    #print('Failed to Convert: {0}'.format(file_path))



word.Quit()

Converting: C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/Dahdeh, Marwen - WE 503.doc

com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Word', "Sorry, we couldn't find your file. Was it moved, renamed, or deleted?\r (C:\\//Users/NIX/Documents/Project/Gith...)", 'wdmain11.chm', 24654, -2146823114), None)

In [8]:
#save_as_docx('../../data/resumes/Dahdeh, Marwen - WE 503.doc')
save_as_docx('C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/Dahdeh, Marwen - WE 503.doc')

com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Word', "Sorry, we couldn't find your file. Was it moved, renamed, or deleted?\r (C:\\//Users/NIX/Documents/Project/Gith...)", 'wdmain11.chm', 24654, -2146823114), None)

In [29]:
for path in paths:
    save_as_docx(path)

com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Word', "Sorry, we couldn't find your file. Was it moved, renamed, or deleted?\r (C:\\//Users/NIX/Documents/Project/Gith...)", 'wdmain11.chm', 24654, -2146823114), None)

In [76]:
!pwd

/c/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/src/draft_scripts

In [86]:
# paths = glob.glob('../../data/resumes/*.doc')
paths = glob('C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes/*.doc')

In [87]:
paths

['C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Dahdeh, Marwen - WE 503.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Gendron-Poirier, William - WE 518.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Hanmore, Will - TB 704.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Khan, Nabeel - WE 1076.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Krakana, Francis - WE 542.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Lachance, Stephanie - WE 521.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Rabbani, Bilal - TB 461.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Yang, Jimmy - WE 545.doc',
 'C:/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/data/resumes\\Yang, Lijia - WW 253.doc']

In [88]:
#import glob

# Determine how many resumes are there
docx_files = glob("../../data/resumes/*.docx")
pdf_files = glob("../../data/resumes/*.pdf")

files = set(docx_files + pdf_files)
files_list = list(files)
print ("%d files identified" %len(files))

info_dict = {}
count = 0

for file in files_list:
    
    print("Reading File %s"% count +" " +file)
    count += 1 
    

    file_name = file
    data, file_type = readFile(file)   
    
    info_dict.setdefault("file_name",[]).append(file_name)
    info_dict.setdefault("file_type",[]).append(file_type)
    #info_dict.setdefault("data",[]).append(data)
    info_dict.setdefault("data",[]).append(data.split("\n"))
    
info_df = pd.DataFrame(info_dict)

1 files identified
Reading File 0 ../../data/resumes\Ahammed, Kawser - WW 284.docx

In [62]:
info_df

,file_name,file_type,data
0,"../../data/resumes\Ahammed, Kawser - WW 284.docx",docx,"[Kawser Ahammed, 414-1225 Moss Avenue, Saskato..."

In [184]:
info_df.iloc[60].data

['Kawser Ahammed',
 '414-1225 Moss Avenue, Saskatoon, SK, S7H5B1           Cell: (306) 881-1571, Email: kawser.dc@gmail.com',
 '',
 'HIGHLIGHTS OF QUALIFICATIONS',
 '2+ years experience in Direct Sales and Customer service',
 'Certificate of service best customer service (Saskatchewan Tourism Education Council)',
 'Proficient in using Microsoft Office',
 'Multilingual: English, Hindi, Urdu and Bangla',
 '',
 'SKILLS AND EXPERIENCE',
 'Sales & Customer Service Skills:',
 'Understanding customer needs and suggesting solutions',
 'Ability to work one-on-one with patients and determine individual needs',
 'Reading customer minds and directs them to a long-term profitable transaction',
 'Strong Customer Service oriented',
 '',
 'Supporting Skills:',
 'Respond well to new challenges and opportunities to learn',
 'Detail oriented and works with a high degree of accuracy',
 'Profound ability to multitask in a fast-paced environment',
 'Exceptional interpersonal and organizational skills',
 'Good sense of time management',
 '………………………………………………………………………………………………………………………………………………………………….',
 'EXEPERIENCE SYNOPSIS',
 'Bookkeeper, 786 Accounting & Tax, Saskatoon, SK                                                          May 2019- Continuing',
 'Connected Solution Specialist, Bestbuy, Saskatoon, SK                                        October 2017- August 2018',
 'Sales Associate, Old Navy, Saskatoon, SK                                                                  August 2017- January 2018',
 'Storefront Attendant, Tim Horton’s, Saskatoon, SK                                              September 2015- June 2016',
 'Business Officer, Square Hospitals Ltd, Dhaka, Bangladesh                                         March 2014- June 2015',
 'Admin Officer, Community Medical College & Hospital, Dhaka, Bangladesh       May 2012- February 2014',
 '',
 'EDUCATION',
 'Accounting Certificate, Saskatchewan Polytechnic, Saskatoon, SK                                                               2019',
 'Bachelor of Business Studies, National University, Bangladesh                                                                    2010',
 '',
 'REFERENCE ',
 'Arsalan Neshan, Sales Supervisor, Best Buy, Cell: 306-881-0536, Email: aneshan@bestbuycanada.ca',
 'Panna Dev, Operation Manager, Old Navy, Cell: 306-850-5392, Email: panna_rds14@yahoo.com']

In [105]:
lines=[]
for element in line1.split():
    print(nltk.word_tokenize(element))
    lines.append(nltk.word_tokenize(element))

['414-1225']
['Moss']
['Avenue', ',']
['Saskatoon', ',']
['SK', ',']
['S7H5B1']
['Cell', ':']
['(', '306', ')']
['881-1571', ',']
['Email', ':']
['kawser.dc', '@', 'gmail.com']

In [106]:
lines

[['414-1225'],
 ['Moss'],
 ['Avenue', ','],
 ['Saskatoon', ','],
 ['SK', ','],
 ['S7H5B1'],
 ['Cell', ':'],
 ['(', '306', ')'],
 ['881-1571', ','],
 ['Email', ':'],
 ['kawser.dc', '@', 'gmail.com']]

In [107]:
for element in lines:
   print(nltk.pos_tag(element))

[('414-1225', 'JJ')]
[('Moss', 'NN')]
[('Avenue', 'NNP'), (',', ',')]
[('Saskatoon', 'NN'), (',', ',')]
[('SK', 'NNP'), (',', ',')]
[('S7H5B1', 'NN')]
[('Cell', 'NN'), (':', ':')]
[('(', '('), ('306', 'CD'), (')', ')')]
[('881-1571', 'CD'), (',', ',')]
[('Email', 'NN'), (':', ':')]
[('kawser.dc', 'NN'), ('@', 'CD'), ('gmail.com', 'NN')]

In [92]:
def preprocess(document):
        '''
        Information Extraction: Preprocess a document with the necessary POS tagging.
        Returns three lists, one with tokens, one with POS tagged lines, one with POS tagged sentences.
        Modules required: nltk
        '''
        try:
            # Try to get rid of special characters
#             try:
#                 document = document.decode('ascii', 'ignore')
#             except:
#                 document = document.encode('ascii', 'ignore')
            # Newlines are one element of structure in the data
            # Helps limit the context and breaks up the data as is intended in resumes - i.e., into points
            lines = [el.strip() for el in document.split("\n") if len(el) > 0]  # Splitting on the basis of newlines 
            lines = [nltk.word_tokenize(el) for el in lines]    # Tokenize the individual lines
            lines = [nltk.pos_tag(el) for el in lines]  # Tag them
            # Below approach is slightly different because it splits sentences not just on the basis of newlines, but also full stops 
            # - (barring abbreviations etc.)
            # But it fails miserably at predicting names, so currently using it only for tokenization of the whole document
            sentences = nltk.sent_tokenize(document)    # Split/Tokenize into sentences (List of strings)
            sentences = [nltk.word_tokenize(sent) for sent in sentences]    # Split/Tokenize sentences into words (List of lists of strings)
            tokens = sentences
            sentences = [nltk.pos_tag(sent) for sent in sentences]    # Tag the tokens - list of lists of tuples - each tuple is (<word>, <tag>)
            # Next 4 lines convert tokens from a list of list of strings to a list of strings; basically stitches them together
            dummy = []
            for el in tokens:
                dummy += el
            tokens = dummy
            # tokens - words extracted from the doc, lines - split only based on newlines (may have more than one sentence)
            # sentences - split on the basis of rules of grammar
            return tokens, lines, sentences
        except Exception as e:
            print(e)

In [93]:
tokens, lines, sentences = preprocess(resume_data)

In [96]:
lines[:5]

[[('Kawser', 'NNP'), ('Ahammed', 'NNP')],
 [('414-1225', 'JJ'),
  ('Moss', 'NNP'),
  ('Avenue', 'NNP'),
  (',', ','),
  ('Saskatoon', 'NNP'),
  (',', ','),
  ('SK', 'NNP'),
  (',', ','),
  ('S7H5B1', 'NNP'),
  ('Cell', 'NNP'),
  (':', ':'),
  ('(', '('),
  ('306', 'CD'),
  (')', ')'),
  ('881-1571', 'CD'),
  (',', ','),
  ('Email', 'NNP'),
  (':', ':'),
  ('kawser.dc', 'NN'),
  ('@', 'NN'),
  ('gmail.com', 'NN')],
 [('HIGHLIGHTS', 'NNP'), ('OF', 'NNP'), ('QUALIFICATIONS', 'NNP')],
 [('2+', 'CD'),
  ('years', 'NNS'),
  ('experience', 'NN'),
  ('in', 'IN'),
  ('Direct', 'NNP'),
  ('Sales', 'NNS'),
  ('and', 'CC'),
  ('Customer', 'NNP'),
  ('service', 'NN')],
 [('Certificate', 'NNP'),
  ('of', 'IN'),
  ('service', 'NN'),
  ('best', 'RBS'),
  ('customer', 'NN'),
  ('service', 'NN'),
  ('(', '('),
  ('Saskatchewan', 'NNP'),
  ('Tourism', 'NNP'),
  ('Education', 'NNP'),
  ('Council', 'NNP'),
  (')', ')')]]

In [130]:
files = set(docx_files + pdf_files)
files

{'resumes/Ahammed, Kawser - WW 284.docx'}

In [113]:
os.chdir("/Users/Robert_Mac/Documents/GitHub/Labs/Block_7/Glentel/")

In [1]:
!pwd

/c/Users/NIX/Documents/Project/Github/fork/591_capstone_2020-glentel-mds/src/draft_scripts

In [123]:

docx_files = glob.glob("resumes/*.docx")
docx_files

['resumes/Ahammed, Kawser - WW 284.docx',
 'resumes/~$ammed, Kawser - WW 284.docx']

## Summary of what actually works so far => Importing docx

In [183]:
import os, nltk, glob
import pandas as pd
import numpy as np
from docx import Document

In [119]:
# Convert from doc to docx using word application
import win32com.client

word = win32com.client.Dispatch("Word.Application")
#word.visible = 0
count = 0
file_dir = "../../data/resumes/"
file_convert_log = []

# Read and convert files
for root, dirs, files in os.walk(file_dir):
    for file in files:
        
        file_extension = file.split(".")[-1]
        
        if file_extension in ["docx", "rtf", "pdf", "txt", "xlsx"]: #Skip other file types
            skip=True
            continue
        elif file.startswith('~'): #Ignore hidden files
            skip=True
            continue
        else: 
            file_name = file.split(".")[0]
            #print(file_name)
            file_path_name = os.path.join(root, file_name)
            #print(file_path)
            in_file = os.path.abspath("{}.doc".format(file_path_name))
            out_file = os.path.abspath("{}.docx".format(file_path_name))
            
            count += 1 
            print("Reading file %s"% count +" " +file)
            #print("processing file:", file)
        try:
            wb = word.Documents.Open(in_file)
            wb.SaveAs2(out_file, FileFormat=16) # file format for docx = 16
            file_convert_log.append(file)
        except TypeError:
            continue
            wb.Close()

word.Quit()

# Save convert log to external txt file
file_path_name = os.path.join(root, 'doc_to_docx_log.txt')
f = open(file_path_name,'w')
f.write("Total of {} files converted\n".format(len(file_convert_log)))
for item in file_convert_log:
    f.write(item+'\n')
f.close() 

print('Done!')
print("\nSuccesfully converted {} files".format(len(file_convert_log)))
print("Files converted saved in `doc_to_docx_log.txt`.")

Reading file 1 Abrum, Nabil - WE 540 - N7R.doc
Reading file 2 Ahmad, Waqar - WE 162 - MU9.doc
Reading file 3 Ahmadzai, Masood - TB 142 - N5D.doc
Reading file 4 Akers, Dustin - WW 136 - N74.doc
Reading file 5 Beaulieu-Daye, Victoria - WE 1055 - MWF.doc
Reading file 6 Delaney, Jeremy - TB 702 - MTI.doc
Reading file 7 Ha, Gilbert - WW 252 - N2N.doc
Reading file 8 Hanmore, Will - TB 704.doc
Reading file 9 Hayes, James - WW 299 - MWT.doc
Reading file 10 Kapoor, Siddharth - WW 299 - N3Z.doc
Reading file 11 Khan, Nabeel - WE 1076.doc
Reading file 12 Kumane, Kiarra - WW 383 - N4V.doc
Reading file 13 Le, Tran Anh Ly - WW 127 - MRW.doc
Reading file 14 Molnar, Connor - TB 460 - KVU.doc
Reading file 15 Momin, Anil - WW 341 - MSY.doc
Reading file 16 Momin, Anil - WW 372 - MSY.doc
Reading file 17 More, Kiran - WE 51 - N1J.doc
Reading file 18 Musa, Syed M - TB 422 - KWP.doc
Reading file 19 Patel, Dhruvkumar - WE 1169 - JMS.doc
Reading file 20 Pattimore, Derek - WE 533 - N8J.doc
Reading file 21 Rabbani, Bilal - TB 461.doc
Reading file 22 Schillemat, Christine - WE 591 - N3E.doc
Reading file 23 Soufan, Al - WW 331 - N7G.doc
Reading file 24 Wadhwa, Varun - WE 548 - N5W.doc
Reading file 25 Xiong, Junzhe - TB 426 - MTR.doc
Reading file 26 Yang, Jimmy - WE 545.doc
Reading file 27 Yang, Lijia - WW 253.doc
Reading file 28 Yang, Shih Min - WW 148 - N8A.doc
Done!

Succesfully converted 28 files
Files converted saved in `doc_to_docx_log.txt`.

In [120]:
#Move converted files doc_files folder

## Read file into a list
file_dir = "../../data/resumes/"
file_path = os.path.join(file_dir, 'doc_to_docx_log.txt')

with open(file_path) as f:
    file_list = list(f)
file_list = list(map(lambda s: s.strip(), file_list))[1:] #remove "\n from text"

# Make doc_files directoty
folder_path = os.path.join(file_dir, 'doc_files')
try:
    os.mkdir(folder_path)
except Exception as e:
    print(e) 
    pass

# Move files
for item in file_list:
    source = os.path.join(file_dir, item)
    destination = os.path.join(folder_path+'/', item)
    os.rename(source, destination)
    record = str(item)+' moved into'+folder_path
    print(record)
print("Done!")

Abrum, Nabil - WE 540 - N7R.doc moved into../../data/resumes/doc_files
Ahmad, Waqar - WE 162 - MU9.doc moved into../../data/resumes/doc_files
Ahmadzai, Masood - TB 142 - N5D.doc moved into../../data/resumes/doc_files
Akers, Dustin - WW 136 - N74.doc moved into../../data/resumes/doc_files
Beaulieu-Daye, Victoria - WE 1055 - MWF.doc moved into../../data/resumes/doc_files
Delaney, Jeremy - TB 702 - MTI.doc moved into../../data/resumes/doc_files
Ha, Gilbert - WW 252 - N2N.doc moved into../../data/resumes/doc_files
Hanmore, Will - TB 704.doc moved into../../data/resumes/doc_files
Hayes, James - WW 299 - MWT.doc moved into../../data/resumes/doc_files
Kapoor, Siddharth - WW 299 - N3Z.doc moved into../../data/resumes/doc_files
Khan, Nabeel - WE 1076.doc moved into../../data/resumes/doc_files
Kumane, Kiarra - WW 383 - N4V.doc moved into../../data/resumes/doc_files
Le, Tran Anh Ly - WW 127 - MRW.doc moved into../../data/resumes/doc_files
Molnar, Connor - TB 460 - KVU.doc moved into../../data/resumes/doc_files
Momin, Anil - WW 341 - MSY.doc moved into../../data/resumes/doc_files
Momin, Anil - WW 372 - MSY.doc moved into../../data/resumes/doc_files
More, Kiran - WE 51 - N1J.doc moved into../../data/resumes/doc_files
Musa, Syed M - TB 422 - KWP.doc moved into../../data/resumes/doc_files
Patel, Dhruvkumar - WE 1169 - JMS.doc moved into../../data/resumes/doc_files
Pattimore, Derek - WE 533 - N8J.doc moved into../../data/resumes/doc_files
Rabbani, Bilal - TB 461.doc moved into../../data/resumes/doc_files
Schillemat, Christine - WE 591 - N3E.doc moved into../../data/resumes/doc_files
Soufan, Al - WW 331 - N7G.doc moved into../../data/resumes/doc_files
Wadhwa, Varun - WE 548 - N5W.doc moved into../../data/resumes/doc_files
Xiong, Junzhe - TB 426 - MTR.doc moved into../../data/resumes/doc_files
Yang, Jimmy - WE 545.doc moved into../../data/resumes/doc_files
Yang, Lijia - WW 253.doc moved into../../data/resumes/doc_files
Yang, Shih Min - WW 148 - N8A.doc moved into../../data/resumes/doc_files
Done!

In [392]:
# Read docx files 
# import os
#from docx import Document

def readFile(fileName):
        '''
        Reads docx resume given its name as a string.
        Modules required: os, Document (from docx)
        packages required: python-docx
        Return:
        output_1: resume line by line
        output_2: resume plain text
        '''
        extension = fileName.split(".")[-1]
        
        if extension == "docx":
            try:
                document = Document(fileName)
                output_1 = "\n".join([pgraph.text for pgraph in document.paragraphs]) # By line mode
                output_1 = output_1.split("\n")
                output_2 = ' '.join([pgraph.text for pgraph in document.paragraphs]) # Plain text mode
                return output_1, output_2, extension
            
            except:
                print('####### WARNING ####### WARNING ####### WARNING #######')
                print(fileName+' ========> IS EMPTY ')
                print('####### WARNING ####### WARNING ####### WARNING #######')
                return 'NO_DATA', 'NO_DATA', extension
                pass
        
#         elif extension == "pdf":
#             pass
#             try:
#                 return convertPDFToText(fileName), extension
#             except:
#                 return ''
#                 pass
        else:
            print('Unsupported format')
            return '', '', ''

In [393]:
#import glob
## READ DOCX FILES

# Determine how many resume files are there
docx_files = glob.glob("../../data/resumes/*.docx")
pdf_files = glob.glob("../../data/resumes/*.pdf")

files = set(docx_files + pdf_files)
files_list = list(files)
print("%d files identified" %len(files))
print("%d docx files " %len(docx_files))
print("%d pdf files" %len(pdf_files))

info_dict = {}
files_missing_unique_id = []
files_missing_store_id = []

count = 0 # Count initialization

print("\n############ Processing docx files #############\n")

file_dir = "../../data/resumes/"

# Read docx files
for root, dirs, files in os.walk(file_dir): #This also list files inside sub directories
    for file in files:
        
        file_extension = file.split(".")[-1]
        
        if file_extension in ["doc","rtf", "pdf", "txt", "xlsx"]: #Skip other file types
            skip=True
            continue
        if file.startswith('~'): #Ignore hidden files
            skip=True
            continue
        else:
            file_name = file.split(".")[0]
            #print(file_name)
            file_path_name = os.path.join(root, file)
            #print(file_path_name)
            
# Read Resume data and extension
        count += 1 
        print("Reading file %s"% count +" " +file)
        
        resume_bline, resume_text, file_type = readFile(file_path_name)   # Call read function
        
# Read employee name, store_id and unique id from meta data
        splits = file_name.split(" - ")
        employee_name = splits[0]
        if len(splits) != 1:
            store_id = splits[1]
            if len(splits) == 3:
                unique_id = splits[2]
            else: 
                unique_id = 'NO_UID'
                #unique_id = ''
                files_missing_unique_id.append(file)
                print(employee_name+' ========> DOES NOT HAVE UNIQUE ID')
        else: 
            store_id = 'NO_SID'
            #store_id = ''
            files_missing_store_id.append(file)
            print(employee_name+' ========> DOES NOT STORE ID')

# Save properties to dictionary
        info_dict.setdefault("file_name",[]).append(file_name)
        info_dict.setdefault("file_type",[]).append(file_type)
        info_dict.setdefault("meta_e_name",[]).append(employee_name)
        info_dict.setdefault("meta_s_id",[]).append(store_id)
        info_dict.setdefault("meta_u_id",[]).append(unique_id)
        info_dict.setdefault("resume_bline",[]).append(resume_bline) #Show imported resume by line
        info_dict.setdefault("resume_text",[]).append(resume_text) #Show imported resume by line

# Create missing uid and sid files
file_path_name = os.path.join(file_dir, 'docx_files_missing_meta_unique_id.txt')
print(file_path_name)
f = open(file_path_name,'w')
f.write("Total of {} employees are missing unique_ids\n".format(len(files_missing_unique_id)))
for item in files_missing_unique_id:
    f.write(item+'\n')
f.close() 

file_path_name = os.path.join(file_dir, 'docx_files_missing_meta_store_id.txt')
f = open(file_path_name,'w')
f.write("Total of {} employees are missing store_ids\n".format(len(files_missing_store_id)))
for item in files_missing_store_id:
    f.write(item+'\n')
f.close() 

print("\nTotal of {} employees are missing unique_ids".format(len(files_missing_unique_id)))
print("Total of {} employees are missing store_ids\n".format(len(files_missing_store_id)))

print("employees missing unique ids saved in `files_missing_meta_unique_id.txt`.")
print("employees missing store ids saved in `files_missing_meta_store_id.txt`.")
            
#Convert to pandas dataframe    
docx_df = pd.DataFrame(info_dict)
print("\nSave results into docx_df pandas dataframe variable")

# Export as csv file to the output folder
ouput_path_name = "../../data/output/docx_english_resume.csv"
docx_df.to_csv(ouput_path_name)
print("Writing CSV file to {} \n".format(ouput_path_name))

print("Done!")

486 files identified
258 docx files
228 pdf files

############ Processing docx files #############

Reading file 1 Abbasi, Samiee Z - WW 374 - N42.docx
Reading file 2 Abrams, James - WW 851 - MZV.docx
Reading file 3 Abrum, Nabil - WE 540 - N7R.docx
Reading file 4 Ahammed, Kawser - WW 284.docx
Ahammed, Kawser ========> DOES NOT HAVE UNIQUE ID
Reading file 5 Ahmad, Waqar - WE 162 - MU9.docx
Reading file 6 Ahmadzai, Masood - TB 142 - N5D.docx
Reading file 7 Ahmed, Mubaraz - TB 454 - N0T.docx
Reading file 8 Ahmed, Zarif - WE 1316 - N4P.docx
Reading file 9 Akash, Sadana - WE 162 - MXA.docx
Reading file 10 Akers, Dustin - WW 136 - N74.docx
Reading file 11 Ali, Allie - WE 1217.docx
Ali, Allie ========> DOES NOT HAVE UNIQUE ID
Reading file 12 Ali, Tashfi - WW 852.docx
Ali, Tashfi ========> DOES NOT HAVE UNIQUE ID
Reading file 13 Allen, Shelby - WW 802 - N7E.docx
Reading file 14 Allouch, Amal - WE 531 - N58.docx
Reading file 15 Amiri, Mohammad - WW 337 - NDG.docx
Reading file 16 Anand, Pragun - WE 51 -MQB.docx
Anand, Pragun ========> DOES NOT HAVE UNIQUE ID
Reading file 17 Ansari Rad, Naser - WW 850.docx
Ansari Rad, Naser ========> DOES NOT HAVE UNIQUE ID
Reading file 18 Antler, Dakota - WE 593.docx
Antler, Dakota ========> DOES NOT HAVE UNIQUE ID
Reading file 19 Arora, Himanshu - WE 255 - N6D.docx
Reading file 20 Arseneault, Joel - WW 804.docx
Arseneault, Joel ========> DOES NOT HAVE UNIQUE ID
Reading file 21 Askari, Behrouz - WW 388 - N1W.docx
Reading file 22 Atkinson, Brandon - WE 591 - NDS.docx
Reading file 23 Azarraga, Jacqean - WW 253.docx
Azarraga, Jacqean ========> DOES NOT HAVE UNIQUE ID
Reading file 24 Badick, Erik - WE 161 - NE9.docx
Reading file 25 Bain, Cora - TB 459 - MUL.docx
Reading file 26 Bajwa, Manpreet - WETC 1112 - MWE.docx
Reading file 27 Bajwa, Satvir - WW 253 - LKQ.docx
Reading file 28 Baker, Kody - WE 1105.docx
Baker, Kody ========> DOES NOT HAVE UNIQUE ID
Reading file 29 Balche, Naji - TB 441 - N2I.docx
Reading file 30 Barker, Alec - WE 258 - N5C.docx
Reading file 31 Basdeo, Kavi - WW 338.docx
Basdeo, Kavi ========> DOES NOT HAVE UNIQUE ID
Reading file 32 Bassi, Tarundeep - TB 461 - MRE.docx
Reading file 33 Basso, Michael - WE 257 - N8U.docx
Reading file 34 Beaulieu-Daye, Victoria - WE 1055 - MWF.docx
Reading file 35 Bell, Sarah - WE 1265.docx
Bell, Sarah ========> DOES NOT HAVE UNIQUE ID
Reading file 36 Bhoumik, Mitu - TB 283 - N80.docx
Reading file 37 Bibic, Andreas - WW 353 - LZR.docx
Reading file 38 Bilgesu, Enes - TB 427 - N5L.docx
Reading file 39 Bois, Kevin - TB 421- MVT.docx
Bois, Kevin ========> DOES NOT HAVE UNIQUE ID
Reading file 40 Bolat, Ece - TB 422.docx
Bolat, Ece ========> DOES NOT HAVE UNIQUE ID
Reading file 41 Brar, Surat - WW 148 - MQG.docx
Reading file 42 Brining, Christopher - WE 1128 - N39.docx
Reading file 43 Bronson, Jordan - TB 704 -NDW.docx
Bronson, Jordan ========> DOES NOT HAVE UNIQUE ID
Reading file 44 Broomes, Tristan - WE 537 - NDZ.docx
Reading file 45 Brown, Taylor - WW 132.docx
Brown, Taylor ========> DOES NOT HAVE UNIQUE ID
Reading file 46 Butt, Wahhaj Ahmed - WW 386.docx
Butt, Wahhaj Ahmed ========> DOES NOT HAVE UNIQUE ID
Reading file 47 Carey, Brent - WW 322.docx
Carey, Brent ========> DOES NOT HAVE UNIQUE ID
Reading file 48 Chan, Alexandre - WW 123 - JQB.docx
Reading file 49 Chandel, Samarendra - WE 1316.docx
Chandel, Samarendra ========> DOES NOT HAVE UNIQUE ID
Reading file 50 Chaudhari, Dharmik - TB 422 - N12.docx
Reading file 51 Chaudhary, Apoorva - WW 281 - N4D.docx
Reading file 52 Chia, Emily - WW 383 - N14.docx
Reading file 53 Choi, Nathan - TB 180 - N1U.docx
Reading file 54 Choudhry, Furqan - WE 1217.docx
Choudhry, Furqan ========> DOES NOT HAVE UNIQUE ID
Reading file 55 Chowdhary, Samita - WE 259 - N8T.docx
Reading file 56 Chowdhury, Muhammad Nuhel - WE 595 - N8E.docx
Reading file 57 Chughtai, Muhammad - WW 382 - N6V.docx
Reading file 58 Chung, Young - WE 535 - MRI.docx
Reading file 59 Cole, Jason - WE 55 - NE1.docx
Reading file 60 Cunningham, Benjamin James - WW 357.docx
Cunningham, Benjamin James ========> DOES NOT HAVE UNIQUE ID
Reading file 61 Curry, John Paul - TB 447 - B5H.docx
Reading file 62 Dallaire, Jonathan - WE 514.docx
Dallaire, Jonathan ========> DOES NOT HAVE UNIQUE ID
Reading file 63 Dardenne, Elena - WW 852 - N1G.docx
Reading file 64 Delaney, Jeremy - TB 702 - MTI.docx
Reading file 65 Dor-Traynor, Corey - WW 330 - MWK.docx
Reading file 66 Du, Raymond - WE 547.docx
Du, Raymond ========> DOES NOT HAVE UNIQUE ID
Reading file 67 Duggal, Kunal - WE 1076 - MRF.docx
Reading file 68 Ebadi, Massy - WE 547 - MQV.docx
Reading file 69 Ehrlich, Josh - WE 256.docx
Ehrlich, Josh ========> DOES NOT HAVE UNIQUE ID
Reading file 70 El Merhebi, Saad - WW 340 - N28.docx
Reading file 71 El-Osta, Ryanne - WW 321 - M55.docx
Reading file 72 Elbajegni, Omar - WW 295 - N1N.docx
Reading file 73 Elejel, Ali - WE 530 - N67.docx
Reading file 74 Eustaquio, Melquea - WE 548 - MTT.docx
Reading file 75 Facey, Shantal - WW 123.docx
Facey, Shantal ========> DOES NOT HAVE UNIQUE ID
Reading file 76 Feng, Zoe - TB 180 - MU8.docx
Reading file 77 Flegel, Austin - WW 120 - MTH.docx
Reading file 78 Francis, Lacy - WW 856 - N92.docx
Reading file 79 Fratric, NIcholas - WE 1157 - N5E.docx
Reading file 80 Gandhi, Pinal - WW 329.docx
Gandhi, Pinal ========> DOES NOT HAVE UNIQUE ID
Reading file 81 Gardiner, Michael W - WE 511 - N6S.docx
Reading file 82 Gaurav, Gaurav - WE 161 - NEB.docx
Reading file 83 George, George - WW 293 - N66.docx
Reading file 84 Gill, Bikramjeet - WW 298 - N4C.docx
Reading file 85 Gill, Karan - WE 156 - N2E.docx
Reading file 86 Gilles, Luigi - WW 365.docx
Gilles, Luigi ========> DOES NOT HAVE UNIQUE ID
Reading file 87 Golam, Moe - WE 1105 - N6Y.docx
Reading file 88 Greenbird, Cassia - WE 591.docx
Greenbird, Cassia ========> DOES NOT HAVE UNIQUE ID
Reading file 89 Grewal, Amandeep - WW 244 - MUT.docx
Reading file 90 Gujral, Sandeep Singh - WW 349.docx
Gujral, Sandeep Singh ========> DOES NOT HAVE UNIQUE ID
Reading file 91 Gunasegaram, Abimanyu - TB 432.docx
Gunasegaram, Abimanyu ========> DOES NOT HAVE UNIQUE ID
Reading file 92 Ha, Gilbert - WW 252 - N2N.docx
Reading file 93 Hamatto, Safia - WW 389 - MQI.docx
Reading file 94 Hanmore, Will - TB 704.docx
Hanmore, Will ========> DOES NOT HAVE UNIQUE ID
Reading file 95 Harrouk, Toufik - TB 102 - N2O.docx
Reading file 96 Hasan, Rhidoy - WE 161 - MXH.docx
Reading file 97 Hasani, Akbar Ali - WW 340 - N7F.docx
Reading file 98 Hayes, James - WW 299 - MWT.docx
Reading file 99 Hong, Tony - TB 420 - N2P.docx
Reading file 100 Idris, Inas - WW 293 - N8S.docx
Reading file 101 Ifraimov, Nathan - WW 368 - N8G.docx
Reading file 102 Irving, Quinn - WE 1112.docx
Irving, Quinn ========> DOES NOT HAVE UNIQUE ID
Reading file 103 Janmohamed, Raheem - TB 171 - MQZ.docx
Reading file 104 Jaouhar, Ahmed - TB 428.docx
Jaouhar, Ahmed ========> DOES NOT HAVE UNIQUE ID
Reading file 105 Johnson, Jessica - TB 454 - N9D.docx
Reading file 106 Joshi, Sahil - WW 121 - MQ2.docx
Reading file 107 Kadhem, Abbaas - TB 441 - N18.docx
Reading file 108 Kainth, Manmeet - TB 173 - LWG.docx
Reading file 109 Kapoor, Siddharth - WW 299 - N3Z.docx
Reading file 110 Kaur, Ramandeep - WW 281 - MYH.docx
Reading file 111 Kaur, Sukhpreet - WW 1157 - N7J.docx
Reading file 112 Khalil, Khaled - WW 359 - NDV.docx
Reading file 113 Khan, Abbas - WW 334.docx
Khan, Abbas ========> DOES NOT HAVE UNIQUE ID
Reading file 114 Khan, Faiz - WW 247 - N5I.docx
Reading file 115 Khan, Haris - TB 413 - N9N.docx
Reading file 116 Khan, Nabeel - WE 1076.docx
Khan, Nabeel ========> DOES NOT HAVE UNIQUE ID
Reading file 117 Khan, Sharmeen - TB 452 - N9T.docx
Reading file 118 Khan, Tasif - WW 386.docx
Khan, Tasif ========> DOES NOT HAVE UNIQUE ID
Reading file 119 Khanafer, Yarah - WE 530 - N3V.docx
Reading file 120 Khoja, Azeezuddin - WE 526 - MS0.docx
Reading file 121 Kieffer, Adam - WE 252 - N8C.docx
Reading file 122 Kipnis, Ryan - TB 468.docx
Kipnis, Ryan ========> DOES NOT HAVE UNIQUE ID
Reading file 123 Kirby, Taylor - WE 158 - N7K.docx
Reading file 124 Krchov, Jaime - WE 152 - N4E.docx
Reading file 125 Kumane, Kiarra - WW 383 - N4V.docx
Reading file 126 Laqui, Marley - WE 255.docx
Laqui, Marley ========> DOES NOT HAVE UNIQUE ID
Reading file 127 LaRose, Lise - TB 604 - N8I.docx
Reading file 128 Le, Anthony - WW 351 - MSX.docx
Reading file 129 Le, Cuong - TB 455 - NDL.docx
Reading file 130 Le, Tran Anh Ly - WW 127 - MRW.docx
Reading file 131 LeBlanc, Jean-Michel - WE 551.docx
LeBlanc, Jean-Michel ========> DOES NOT HAVE UNIQUE ID
Reading file 132 Lepage, Robert - WE 1069.docx
Lepage, Robert ========> DOES NOT HAVE UNIQUE ID
Reading file 133 Li, Mingxiao - WW 280.docx
Li, Mingxiao ========> DOES NOT HAVE UNIQUE ID
Reading file 134 Lin, HongMin - WE 545 -ND8.docx
Lin, HongMin ========> DOES NOT HAVE UNIQUE ID
Reading file 135 Luthra, Kunal - TB 422 - MW9.docx
Reading file 136 Ly, Gia Buu - TB 174 - MRV.docx
Reading file 137 MacPhail, Christopher - WE 540 - MUA.docx
Reading file 138 Maisuri, Hetvi - WE 54 - N1Q.docx
Reading file 139 Mak, Geoffrey - WW 330 - N4S.docx
Reading file 140 Manzano, Kristine - TB 146 - N3P.docx
Reading file 141 Mavi, Sumeet - TB 469.docx
Mavi, Sumeet ========> DOES NOT HAVE UNIQUE ID
Reading file 142 McCarthy, Kelsey - TB 456 - N2Q.docx
Reading file 143 Mcgregor, Ethan - TB 463 - M7H.docx
Reading file 144 Mcinnis, Peter - WE 519 - N87.docx
Reading file 145 McLean, Alec - TB 702 - N61.docx
Reading file 146 McLeod, Corey - WE 1090 - N21.docx
Reading file 147 Mehrvar, Abtin - TB 458 - N5Z.docx
Reading file 148 Melendez, Luis - WE 593 - NDB.docx
Reading file 149 Mercado, Ericson  - WW 245.docx
Mercado, Ericson  ========> DOES NOT HAVE UNIQUE ID
Reading file 150 Mikkelsen, Dalton - WE 59.docx
Mikkelsen, Dalton ========> DOES NOT HAVE UNIQUE ID
Reading file 151 Milash, Kateryna - WE 152 - N4F.docx
Reading file 152 Miller, Kevin - TB 460 - LCP.docx
Reading file 153 Molnar, Connor - TB 460 - KVU.docx
Reading file 154 Momin, Anil - WW 341 - MSY.docx
Reading file 155 Momin, Anil - WW 372 - MSY.docx
Reading file 156 More, Kiran - WE 51 - N1J.docx
Reading file 157 Mullunde Gopal, Akshitha - WW 356.docx
Mullunde Gopal, Akshitha ========> DOES NOT HAVE UNIQUE ID
Reading file 158 Musa, Syed M - TB 422 - KWP.docx
Reading file 159 Nadeem, Sonia - WW 373 - N1L.docx
Reading file 160 Nafis, Abdullah - WW 336 - MUO.docx
Reading file 161 Nasir, Mohammad - WE 1273 - MVX.docx
Reading file 162 Nguyen, Duy - WE 541 - MW5.docx
Reading file 163 Nouri, Roholah - TB 174 - MRT.docx
Reading file 164 Nurse, Brady - WW 296 - MU6.docx
Reading file 165 O'Brien, Ashley - WE 591.docx
O'Brien, Ashley ========> DOES NOT HAVE UNIQUE ID
Reading file 166 Ol, Peter - WE 552 - MUY.docx
Reading file 167 Patel, Dhruvkumar - WE 1169 - JMS.docx
Reading file 168 Patel, Gaurav - WW 248.docx
Patel, Gaurav ========> DOES NOT HAVE UNIQUE ID
Reading file 169 Patel, Hilori - TB 283 - MWX.docx
Reading file 170 Patel, Nishaben - TB 229.docx
Patel, Nishaben ========> DOES NOT HAVE UNIQUE ID
Reading file 171 Pattimore, Derek - WE 533 - N8J.docx
Reading file 172 Phair, Kayla - WE 257 - N57.docx
Reading file 173 Pham, Danny - WE 547 - N9L.docx
Reading file 174 Phillips, Dominick - WW 248.docx
Phillips, Dominick ========> DOES NOT HAVE UNIQUE ID
Reading file 175 Pires, Anderson - WE 1316 - MTE.docx
Reading file 176 Principio, Celine - WW 343 - N5S.docx
Reading file 177 Pringle, Scott - WW 324.docx
Pringle, Scott ========> DOES NOT HAVE UNIQUE ID
Reading file 178 Qader, Tabasum - WE 1105 - N5U.docx
Reading file 179 Rabbani, Bilal - TB 461.docx
Rabbani, Bilal ========> DOES NOT HAVE UNIQUE ID
Reading file 180 Rahmani, Amirali - WW 143 - N1I.docx
Reading file 181 Rajpurohit, Abhishek - WW 242 - MUG.docx
Reading file 182 Ravi, Shipra - WW 350 - N6U.docx
Reading file 183 Rawding, Kyle - TB 468 - MQO.docx
Reading file 184 Raza Bag, Moteen - WW 345 - MXY.docx
Reading file 185 Razah, Sasha - TB 438 - MWH.docx
Reading file 186 Ren, Jingya Claire - WE 592.docx
Ren, Jingya Claire ========> DOES NOT HAVE UNIQUE ID
Reading file 187 Reynolds, Bradley - TB 460.docx
Reynolds, Bradley ========> DOES NOT HAVE UNIQUE ID
Reading file 188 Riaz, Hassan - WW 349.docx
Riaz, Hassan ========> DOES NOT HAVE UNIQUE ID
Reading file 189 Robinson, Kyle - WW 136.docx
Robinson, Kyle ========> DOES NOT HAVE UNIQUE ID
Reading file 190 Rodriguez-Almonte, Danelle - TB 420 - N1V.docx
Reading file 191 Rose, Victoria - WW 296 - N65.docx
Reading file 192 Roukie, Mohammed - WE 530 - MPI.docx
Reading file 193 Sadeghpour, Seena - WE 547 - MRH.docx
Reading file 194 Saharan, Divya - WW 366 - NDU.docx
Reading file 195 Sahilu, Zadig - WW 365 - MSW.docx
Reading file 196 Saleem, Muhammad Junaid - TB 420 - N17.docx
Reading file 197 Sandhu, Rippanjot - WW 246 - N6H.docx
Reading file 198 Sarkar, Pritam - TB 237 - N4Y.docx
Reading file 199 Sbaih, Derar - WW 364.docx
Sbaih, Derar ========> DOES NOT HAVE UNIQUE ID
Reading file 200 Schillemat, Christine - WE 591 - N3E.docx
Reading file 201 Schwab, Emilly - WE 155 - MRG.docx
Reading file 202 Semera, Jonathan - WE 1248 - MVZ.docx
Reading file 203 Shah, Aagam - TB 101 - MWZ.docx
Reading file 204 Shah, Sachin - WW 370 - N2J.docx
Reading file 205 Shah, Sajjad Ali - TB 416 - NE5.docx
Reading file 206 Shah, Sheena - WW 249.docx
Shah, Sheena ========> DOES NOT HAVE UNIQUE ID
Reading file 207 Shah, Shreyansh - WE 537 - N70.docx
Reading file 208 Shahriar, Hasan - WE 152 - MW4.docx
Reading file 209 Sharma, Abhimanu - WE 258.docx
Sharma, Abhimanu ========> DOES NOT HAVE UNIQUE ID
Reading file 210 Siddik, Mohammad Yashar - TB 283.docx
Siddik, Mohammad Yashar ========> DOES NOT HAVE UNIQUE ID
Reading file 211 Siddiqui, Haseeb - TB 438.docx
Siddiqui, Haseeb ========> DOES NOT HAVE UNIQUE ID
Reading file 212 Sidhu, Jasdeep - WE 1217.docx
Sidhu, Jasdeep ========> DOES NOT HAVE UNIQUE ID
Reading file 213 Singh, Damanjeet - WE 548 - N71.docx
Reading file 214 Singh, Jagdeep - TB 434 - N0U.docx
Reading file 215 Singh, Jagjeet - TB 425 - MZ5.docx
Reading file 216 Singh, Jaswant - WE 544 - K3E.docx
Reading file 217 Singh, Karanbir - WW 246 - N1Z.docx
Reading file 218 Singh, Mandeep - WW 261 - N46.docx
Reading file 219 Singh, Prabhjot - WW 261 - MPV.docx
Reading file 220 Singh, Rupinderpal - WW 137 - N54.docx
Reading file 221 Siraj Ud Din, Muhammad - WW 396 - N69.docx
Reading file 222 Smith, Mandy - TB 462 - LAP.docx
Reading file 223 Soufan, Al - WW 331 - N7G.docx
Reading file 224 Spencer, Nathanael - WE 252 - MRZ.docx
Reading file 225 Streilein, Dustin - WW 134 - MWM.docx
Reading file 226 Sunnapurallapalli, Dilip - TB 454 - MVU.docx
Reading file 227 Syeda, Rida - WW 248.docx
Syeda, Rida ========> DOES NOT HAVE UNIQUE ID
Reading file 228 Szeto, Riely - WE 156 - N8B.docx
Reading file 229 Teeluck, Disha - TB 230 - MTY.docx
Reading file 230 Toukan, Walid - WW 353 - N40.docx
Reading file 231 Tran, Phu - WE 1217.docx
Tran, Phu ========> DOES NOT HAVE UNIQUE ID
Reading file 232 Vanderlinde, David - WE 510 - N4L.docx
Reading file 233 Vasanthakumar, Nagarjan - WW 380 - MV5.docx
Reading file 234 Vellara Seby, Edwin Deepak - WW 341 - MV7.docx
Reading file 235 Verma, Mridul - WE 255 - MTV.docx
Reading file 236 Virani, Rushabh - WE 1316 - N8M.docx
Reading file 237 Wadhwa, Varun - WE 548 - N5W.docx
Reading file 238 Walizada, Navidullah - TB 424 - MWR.docx
Reading file 239 Wassan, Sahil - TB 234.docx
Wassan, Sahil ========> DOES NOT HAVE UNIQUE ID
Reading file 240 Weintz, Simon - WE 1069.docx
Weintz, Simon ========> DOES NOT HAVE UNIQUE ID
Reading file 241 Whitecalf, Reginald - WW 249 - N5N.docx
Reading file 242 Whitelaw, Ashley - TB 460.docx
Whitelaw, Ashley ========> DOES NOT HAVE UNIQUE ID
Reading file 243 Wilkinson, Patrick - WW 113 - NE1.docx
Reading file 244 Wilson, Brittany - WW 339 - N75.docx
Reading file 245 Winnig, Evan - TB 283.docx
Winnig, Evan ========> DOES NOT HAVE UNIQUE ID
Reading file 246 Wong, King Lun Jesse - WE 545.docx
Wong, King Lun Jesse ========> DOES NOT HAVE UNIQUE ID
Reading file 247 Wong, Randy - WE 51 - N6I.docx
Reading file 248 Wylie, Kevin - WE 1273 - N6W.docx
Reading file 249 Xiong, Junzhe - TB 426 - MTR.docx
Reading file 250 Xu, Ningxin - WW 133 - M58.docx
Reading file 251 Yan, YangTian - WE 1128 - N4G.docx
Reading file 252 Yang, Jimmy - WE 545.docx
Yang, Jimmy ========> DOES NOT HAVE UNIQUE ID
Reading file 253 Yang, Lijia - WW 253.docx
Yang, Lijia ========> DOES NOT HAVE UNIQUE ID
Reading file 254 Yang, Shih Min - WW 148 - N8A.docx
Reading file 255 Yen, Shen - WW 145 - N0M.docx
Reading file 256 Yim, Eddy - TB 417 - N1M.docx
Reading file 257 Zaveree, Shehzad - TB 415 - NE0.docx
Reading file 258 Zhu, WeiWei - WW353 - MQF.docx
../../data/resumes/docx_files_missing_meta_unique_id.txt

Total of 70 employees are missing unique_ids
Total of 0 employees are missing store_ids

employees missing unique ids saved in `files_missing_meta_unique_id.txt`.
employees missing store ids saved in `files_missing_meta_store_id.txt`.

Save results into docx_df pandas dataframe variable
Writing CSV file to ../../data/output/docx_english_resume.csv

Done!

In [394]:
docx_df

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text
0,"Abbasi, Samiee Z - WW 374 - N42",docx,"Abbasi, Samiee Z",WW 374,N42,"[Samiee Zahid Abbasi, 61 Muscat Crescent Ajax,...","Samiee Zahid Abbasi 61 Muscat Crescent Ajax, O..."
1,"Abrams, James - WW 851 - MZV",docx,"Abrams, James",WW 851,MZV,"[Michael Abrams , 5214 Gerrish Street, Apt 221...","Michael Abrams 5214 Gerrish Street, Apt 221 C..."
2,"Abrum, Nabil - WE 540 - N7R",docx,"Abrum, Nabil",WE 540,N7R,"[Nabil Abrum, 1042B Beryl Private, Ottawa, ON ...","Nabil Abrum 1042B Beryl Private, Ottawa, ON K1..."
3,"Ahammed, Kawser - WW 284",docx,"Ahammed, Kawser",WW 284,NO_UID,"[Kawser Ahammed, 414-1225 Moss Avenue, Saskato...","Kawser Ahammed 414-1225 Moss Avenue, Saskatoon..."
4,"Ahmad, Waqar - WE 162 - MU9",docx,"Ahmad, Waqar",WE 162,MU9,"[Waqar Ahmad, 158 Fleetwood Crescent, Brampton...","Waqar Ahmad 158 Fleetwood Crescent, Brampton, ..."
...,...,...,...,...,...,...,...
253,"Yang, Shih Min - WW 148 - N8A",docx,"Yang, Shih Min",WW 148,N8A,"[Samson Yang, , ------------------------------...",Samson Yang ---------------------------------...
254,"Yen, Shen - WW 145 - N0M",docx,"Yen, Shen",WW 145,N0M,"[Joey Yen, Richmond, BC, Canada (778)-323-...","Joey Yen Richmond, BC, Canada (778)-323-05..."
255,"Yim, Eddy - TB 417 - N1M",docx,"Yim, Eddy",TB 417,N1M,[ ...,...
256,"Zaveree, Shehzad - TB 415 - NE0",docx,"Zaveree, Shehzad",TB 415,NE0,[SHEHZAD ZAVEREE ...,SHEHZAD ZAVEREE ...
257,"Zhu, WeiWei - WW353 - MQF",docx,"Zhu, WeiWei",WW353,MQF,"[Weiwei Zhu, \tHome Address:\t\t\t\t , 160 cha...",Weiwei Zhu \tHome Address:\t\t\t\t 160 chapel...

In [758]:
# Check CV in 60th row
docx_df.iloc[13].resume_text

'amal.allouch.aa@gmail.com contact #: 647-234-9968 '

In [749]:
def resume_generator(n):
    for i in range(0,n):
        yield i, docx_df.iloc[i].resume_text

resume = resume_generator(258)

In [757]:
next(resume)

StopIteration:

In [751]:
for i in range(1,253):
    next(resume)

In [617]:
# List of Missing UID in the Meta data
docx_df[docx_df["meta_u_id"]=='NO_UID']

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text
3,"Ahammed, Kawser - WW 284",docx,"Ahammed, Kawser",WW 284,NO_UID,"[Kawser Ahammed, 414-1225 Moss Avenue, Saskato...","Kawser Ahammed 414-1225 Moss Avenue, Saskatoon..."
10,"Ali, Allie - WE 1217",docx,"Ali, Allie",WE 1217,NO_UID,"[Allie Ali, (519) 760-5387 \t\t\t4612 Maryvale...",Allie Ali (519) 760-5387 \t\t\t4612 Maryvale R...
11,"Ali, Tashfi - WW 852",docx,"Ali, Tashfi",WW 852,NO_UID,"[Tashfi Tanvir Ali, | Halifax, NS |, | (902) 5...","Tashfi Tanvir Ali | Halifax, NS | | (902) 580-..."
15,"Anand, Pragun - WE 51 -MQB",docx,"Anand, Pragun",WE 51 -MQB,NO_UID,"[Pragun Anand, Contact Info- +1 778-598-2999, ...",Pragun Anand Contact Info- +1 778-598-2999 O...
16,"Ansari Rad, Naser - WW 850",docx,"Ansari Rad, Naser",WW 850,NO_UID,"[, , , , , , \t, , , , , , , , ]",\t
...,...,...,...,...,...,...,...
241,"Whitelaw, Ashley - TB 460",docx,"Whitelaw, Ashley",TB 460,NO_UID,"[Ashley Whitelaw, 220 Brock Street Peterboroug...",Ashley Whitelaw 220 Brock Street Peterborough ...
244,"Winnig, Evan - TB 283",docx,"Winnig, Evan",TB 283,NO_UID,"[Evan Winnig, P.O box 317, Langham, SK, S0K2L0...","Evan Winnig P.O box 317, Langham, SK, S0K2L0 C..."
245,"Wong, King Lun Jesse - WE 545",docx,"Wong, King Lun Jesse",WE 545,NO_UID,"[King Lun Jesse Wong, Richmond Hill, Ontario 6...","King Lun Jesse Wong Richmond Hill, Ontario 647..."
251,"Yang, Jimmy - WE 545",docx,"Yang, Jimmy",WE 545,NO_UID,"[ , , L3S 4P9 , , April 16, 2019, , Manager ,...","L3S 4P9 April 16, 2019 Manager Costco ..."
252,"Yang, Lijia - WW 253",docx,"Yang, Lijia",WW 253,NO_UID,"[Lijia Yang, Mobile: 780-729-9095, Email: , Ad...",Lijia Yang Mobile: 780-729-9095 Email: Addres...

In [618]:
# Read new hire table with uids
#new_hire = pd.read_excel("../../data/resumes/1 - New Hires for CB Resumes Pull.xlsx")

In [1027]:
# Read match list table with uids
match_list = pd.read_csv("../../data/output/matching_list_V1.1.csv")

In [1028]:
match_list.head(2)

,employee_name,employee_code,store,ADP ID,District,Job Title Description,Hire Date,language
0,"Abbasi, Samiee Z",N42,WW 374,25256.0,GTA East,SALES ASSOCIATE,"Thursday, July 18, 2019",English
1,"Abdi, Melika",N3O,TB 146,25237.0,BC East,SALES ASSOCIATE,"Thursday, July 11, 2019",English

In [1029]:
df1 = docx_df.copy()
df2 = match_list.copy()

In [1030]:
# Create dictionary for employee name and code from df2
uid_dict = pd.Series(df2['employee_code'].values, index=df2['employee_name']).to_dict()

In [1031]:
# Create a flag where there is name match to df2 
df1['f_name_match'] = np.where(df1.meta_e_name.isin(uid_dict.keys()), 1, 0)

In [1032]:
# List of employees without a match
df1[df1["f_name_match"]==0]

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match
8,"Akash, Sadana - WE 162 - MXA",docx,"Akash, Sadana",WE 162,MXA,"[, , Akash Sadana, 8 Amazon Court, Brampton, O...","Akash Sadana 8 Amazon Court, Brampton, ON L6...",0
34,"Bell, Sarah - WE 1265",docx,"Bell, Sarah",WE 1265,NO_UID,"[416 Regent Street, Orillia ON L3V4C9, Phone: ...",416 Regent Street Orillia ON L3V4C9 Phone: (51...,0
38,"Bois, Kevin - TB 421- MVT",docx,"Bois, Kevin",TB 421- MVT,NO_UID,"[Kevin Bois, 209 Markland Crescent, \tOttawa (...",Kevin Bois 209 Markland Crescent \tOttawa (Ont...,0
142,"Mcgregor, Ethan - TB 463 - M7H",docx,"Mcgregor, Ethan",TB 463,M7H,"[ETHAN MCGREGOR, Greater Sudbury, ON P3A 3J2, ...","ETHAN MCGREGOR Greater Sudbury, ON P3A 3J2 eth...",0
148,"Mercado, Ericson - WW 245",docx,"Mercado, Ericson",WW 245,NO_UID,"[, , Ericson Mercado, 6115 51 Ave Red Deer AB ...",Ericson Mercado 6115 51 Ave Red Deer AB (T4N...,0
160,"Nasir, Mohammad - WE 1273 - MVX",docx,"Nasir, Mohammad",WE 1273,MVX,"[Education, , Experience, Skills, , , Voluntee...",Education Experience Skills Volunteer (tota...,0

In [1033]:
# Add name column to correct names
df1['employee_name'] = df1['meta_e_name']
df1.head(2)

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name
0,"Abbasi, Samiee Z - WW 374 - N42",docx,"Abbasi, Samiee Z",WW 374,N42,"[Samiee Zahid Abbasi, 61 Muscat Crescent Ajax,...","Samiee Zahid Abbasi 61 Muscat Crescent Ajax, O...",1,"Abbasi, Samiee Z"
1,"Abrams, James - WW 851 - MZV",docx,"Abrams, James",WW 851,MZV,"[Michael Abrams , 5214 Gerrish Street, Apt 221...","Michael Abrams 5214 Gerrish Street, Apt 221 C...",1,"Abrams, James"

In [1034]:
# Inspect df2 using codes from match list
df2[df2["employee_code"]=='MVX']

,employee_name,employee_code,store,ADP ID,District,Job Title Description,Hire Date,language
311,"Nasir, Mohammad Humayon",MVX,WE 1273,24953.0,ONT West - ETC,SALES ASSOCIATE,"Tuesday, April 9, 2019",English

In [1035]:
# Manual rename e_names of unmacthed names 

df1.iloc[8,8] = df2.iloc[14,0] # Akash, Sadana -> Sadana, Akash
df1.iloc[34,8] = df2.iloc[62,0] # Bell, Sarah -> Ball, Sarah
df1.iloc[38,8] = df2.iloc[71,0] # Bois, Kevin -> Bois, Dan Kevin
df1.iloc[142,8] = df2.iloc[275,0] # Mcgregor, Ethan -> McGregor, Ethan
df1.iloc[148,8] = df2.iloc[284,0] # Mercado, Ericson -> Mercado, Ericson?
df1.iloc[160,8] = df2.iloc[311,0] # Nasir, Mohammad -> Nasir, Mohammad Humayon

In [1036]:
# Check if corrections took place using employee_name
df1['f_name_match2'] = np.where(df1.employee_name.isin(uid_dict.keys()), 1, 0)
df1[df1["f_name_match2"]==0]

Empty DataFrame
Columns: [file_name, file_type, meta_e_name, meta_s_id, meta_u_id, resume_bline, resume_text, f_name_match, employee_name, f_name_match2]
Index: []

In [1037]:
df1=df1.drop(columns=["f_name_match2"])

In [1038]:
# Create duplicate column to modify df1 unique ids
df1['employee_code'] = df1['meta_u_id']
df1.head(1)

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code
0,"Abbasi, Samiee Z - WW 374 - N42",docx,"Abbasi, Samiee Z",WW 374,N42,"[Samiee Zahid Abbasi, 61 Muscat Crescent Ajax,...","Samiee Zahid Abbasi 61 Muscat Crescent Ajax, O...",1,"Abbasi, Samiee Z",N42

In [1039]:
#Replace e_code with dictionary values
df1.loc[df1.employee_name.isin(uid_dict.keys()), 'employee_code'] = df1.loc[df1.employee_name.isin(uid_dict.keys()), 'employee_name'].map(uid_dict)
# Check corrections
df1[df1["meta_u_id"]=='NO_UID']

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code
3,"Ahammed, Kawser - WW 284",docx,"Ahammed, Kawser",WW 284,NO_UID,"[Kawser Ahammed, 414-1225 Moss Avenue, Saskato...","Kawser Ahammed 414-1225 Moss Avenue, Saskatoon...",1,"Ahammed, Kawser",NBQ
10,"Ali, Allie - WE 1217",docx,"Ali, Allie",WE 1217,NO_UID,"[Allie Ali, (519) 760-5387 \t\t\t4612 Maryvale...",Allie Ali (519) 760-5387 \t\t\t4612 Maryvale R...,1,"Ali, Allie",MYG
11,"Ali, Tashfi - WW 852",docx,"Ali, Tashfi",WW 852,NO_UID,"[Tashfi Tanvir Ali, | Halifax, NS |, | (902) 5...","Tashfi Tanvir Ali | Halifax, NS | | (902) 580-...",1,"Ali, Tashfi",N15
15,"Anand, Pragun - WE 51 -MQB",docx,"Anand, Pragun",WE 51 -MQB,NO_UID,"[Pragun Anand, Contact Info- +1 778-598-2999, ...",Pragun Anand Contact Info- +1 778-598-2999 O...,1,"Anand, Pragun",MQB
16,"Ansari Rad, Naser - WW 850",docx,"Ansari Rad, Naser",WW 850,NO_UID,"[, , , , , , \t, , , , , , , , ]",\t,1,"Ansari Rad, Naser",N01
...,...,...,...,...,...,...,...,...,...,...
241,"Whitelaw, Ashley - TB 460",docx,"Whitelaw, Ashley",TB 460,NO_UID,"[Ashley Whitelaw, 220 Brock Street Peterboroug...",Ashley Whitelaw 220 Brock Street Peterborough ...,1,"Whitelaw, Ashley",NAC
244,"Winnig, Evan - TB 283",docx,"Winnig, Evan",TB 283,NO_UID,"[Evan Winnig, P.O box 317, Langham, SK, S0K2L0...","Evan Winnig P.O box 317, Langham, SK, S0K2L0 C...",1,"Winnig, Evan",MZ8
245,"Wong, King Lun Jesse - WE 545",docx,"Wong, King Lun Jesse",WE 545,NO_UID,"[King Lun Jesse Wong, Richmond Hill, Ontario 6...","King Lun Jesse Wong Richmond Hill, Ontario 647...",1,"Wong, King Lun Jesse",MXQ
251,"Yang, Jimmy - WE 545",docx,"Yang, Jimmy",WE 545,NO_UID,"[ , , L3S 4P9 , , April 16, 2019, , Manager ,...","L3S 4P9 April 16, 2019 Manager Costco ...",1,"Yang, Jimmy",MXV
252,"Yang, Lijia - WW 253",docx,"Yang, Lijia",WW 253,NO_UID,"[Lijia Yang, Mobile: 780-729-9095, Email: , Ad...",Lijia Yang Mobile: 780-729-9095 Email: Addres...,1,"Yang, Lijia",MYX

In [1040]:
# Create dictionary for employee name and store code from df2
sid_dict = pd.Series(df2['store'].values, index=df2['employee_name']).to_dict()

In [1041]:
# Create duplicate column to assigned store codes from dictionary
df1['store'] = df1['meta_s_id']
df1.head(1)

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code,store
0,"Abbasi, Samiee Z - WW 374 - N42",docx,"Abbasi, Samiee Z",WW 374,N42,"[Samiee Zahid Abbasi, 61 Muscat Crescent Ajax,...","Samiee Zahid Abbasi 61 Muscat Crescent Ajax, O...",1,"Abbasi, Samiee Z",N42,WW 374

In [1042]:
# Replace s_code with dictionary values (sid_dict)
df1.loc[df1.employee_name.isin(sid_dict.keys()), 'store'] = df1.loc[df1.employee_name.isin(sid_dict.keys()), 'employee_name'].map(sid_dict)

In [1043]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   file_name      258 non-null    object
 1   file_type      258 non-null    object
 2   meta_e_name    258 non-null    object
 3   meta_s_id      258 non-null    object
 4   meta_u_id      258 non-null    object
 5   resume_bline   258 non-null    object
 6   resume_text    258 non-null    object
 7   f_name_match   258 non-null    int32
 8   employee_name  258 non-null    object
 9   employee_code  257 non-null    object
 10  store          258 non-null    object
dtypes: int32(1), object(10)
memory usage: 21.3+ KB

In [1044]:
# Create dictionary for employee name and store code from df2
language_dict = pd.Series(df2['language'].values, index=df2['employee_name']).to_dict()
# Create language with dictionary values (language_dict)
df1.loc[df1.employee_name.isin(language_dict.keys()), 'language'] = df1.loc[df1.employee_name.isin(language_dict.keys()), 'employee_name'].map(language_dict)
df1

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code,store,language
0,"Abbasi, Samiee Z - WW 374 - N42",docx,"Abbasi, Samiee Z",WW 374,N42,"[Samiee Zahid Abbasi, 61 Muscat Crescent Ajax,...","Samiee Zahid Abbasi 61 Muscat Crescent Ajax, O...",1,"Abbasi, Samiee Z",N42,WW 374,English
1,"Abrams, James - WW 851 - MZV",docx,"Abrams, James",WW 851,MZV,"[Michael Abrams , 5214 Gerrish Street, Apt 221...","Michael Abrams 5214 Gerrish Street, Apt 221 C...",1,"Abrams, James",MZV,WW 851,English
2,"Abrum, Nabil - WE 540 - N7R",docx,"Abrum, Nabil",WE 540,N7R,"[Nabil Abrum, 1042B Beryl Private, Ottawa, ON ...","Nabil Abrum 1042B Beryl Private, Ottawa, ON K1...",1,"Abrum, Nabil",N7R,WE 540,English
3,"Ahammed, Kawser - WW 284",docx,"Ahammed, Kawser",WW 284,NO_UID,"[Kawser Ahammed, 414-1225 Moss Avenue, Saskato...","Kawser Ahammed 414-1225 Moss Avenue, Saskatoon...",1,"Ahammed, Kawser",NBQ,WW 284,English
4,"Ahmad, Waqar - WE 162 - MU9",docx,"Ahmad, Waqar",WE 162,MU9,"[Waqar Ahmad, 158 Fleetwood Crescent, Brampton...","Waqar Ahmad 158 Fleetwood Crescent, Brampton, ...",1,"Ahmad, Waqar",MU9,WE 162,English
...,...,...,...,...,...,...,...,...,...,...,...,...
253,"Yang, Shih Min - WW 148 - N8A",docx,"Yang, Shih Min",WW 148,N8A,"[Samson Yang, , ------------------------------...",Samson Yang ---------------------------------...,1,"Yang, Shih Min",N8A,WW 148,English
254,"Yen, Shen - WW 145 - N0M",docx,"Yen, Shen",WW 145,N0M,"[Joey Yen, Richmond, BC, Canada (778)-323-...","Joey Yen Richmond, BC, Canada (778)-323-05...",1,"Yen, Shen",N0M,WW 145,English
255,"Yim, Eddy - TB 417 - N1M",docx,"Yim, Eddy",TB 417,N1M,[ ...,...,1,"Yim, Eddy",N1M,TB 417,English
256,"Zaveree, Shehzad - TB 415 - NE0",docx,"Zaveree, Shehzad",TB 415,NE0,[SHEHZAD ZAVEREE ...,SHEHZAD ZAVEREE ...,1,"Zaveree, Shehzad",NE0,TB 415,English
257,"Zhu, WeiWei - WW353 - MQF",docx,"Zhu, WeiWei",WW353,MQF,"[Weiwei Zhu, \tHome Address:\t\t\t\t , 160 cha...",Weiwei Zhu \tHome Address:\t\t\t\t 160 chapel...,1,"Zhu, WeiWei",MQF,WW 353,English

In [1045]:
# Check if language column is the same for all rows comparing first values with the rest
def is_unique(s):
    a = s.to_numpy() 
    return (a[0] == a[1:]).all()

is_unique(df1['language'])

True

In [1046]:
# Alternatively we can check if only english is unique in the column language
pd.unique(df1['language'].values.ravel('K'))

array(['English'], dtype=object)

In [1047]:
# Check for all columns (In case we need it later)
def unique_cols(df):
    a = df.to_numpy() 
    return (a[0] == a[1:]).all(0)
unique_cols(df1)

array([False,  True, False, False, False, False, False, False, False,
       False, False,  True])

In [1048]:
# List of employees without a match
df1[df1["f_name_match"]==0]

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code,store,language
8,"Akash, Sadana - WE 162 - MXA",docx,"Akash, Sadana",WE 162,MXA,"[, , Akash Sadana, 8 Amazon Court, Brampton, O...","Akash Sadana 8 Amazon Court, Brampton, ON L6...",0,"Sadana, Akash",MXA,WE 162,English
34,"Bell, Sarah - WE 1265",docx,"Bell, Sarah",WE 1265,NO_UID,"[416 Regent Street, Orillia ON L3V4C9, Phone: ...",416 Regent Street Orillia ON L3V4C9 Phone: (51...,0,"Ball, Sarah",MVV,WE 1265,English
38,"Bois, Kevin - TB 421- MVT",docx,"Bois, Kevin",TB 421- MVT,NO_UID,"[Kevin Bois, 209 Markland Crescent, \tOttawa (...",Kevin Bois 209 Markland Crescent \tOttawa (Ont...,0,"Bois, Dan Kevin",MVT,TB 421,English
142,"Mcgregor, Ethan - TB 463 - M7H",docx,"Mcgregor, Ethan",TB 463,M7H,"[ETHAN MCGREGOR, Greater Sudbury, ON P3A 3J2, ...","ETHAN MCGREGOR Greater Sudbury, ON P3A 3J2 eth...",0,"McGregor, Ethan",M7H,TB 463,English
148,"Mercado, Ericson - WW 245",docx,"Mercado, Ericson",WW 245,NO_UID,"[, , Ericson Mercado, 6115 51 Ave Red Deer AB ...",Ericson Mercado 6115 51 Ave Red Deer AB (T4N...,0,"Mercado, Ericson",MVD,WW 245,English
160,"Nasir, Mohammad - WE 1273 - MVX",docx,"Nasir, Mohammad",WE 1273,MVX,"[Education, , Experience, Skills, , , Voluntee...",Education Experience Skills Volunteer (tota...,0,"Nasir, Mohammad Humayon",MVX,WE 1273,English

In [446]:
# Export as csv file to the output folder
df1.to_csv("../../data/output/docx_english_resume_matched.csv")

In [777]:
# Check CV is OK
df1.iloc[16].file_name

'Ansari Rad, Naser - WW 850'

In [786]:
# Check CV is OK
df1.iloc[13].resume_bline

['amal.allouch.aa@gmail.com', 'contact #: 647-234-9968', '']

In [759]:
def resume_generator(n):
    for i in range(0,n):
        yield i, df1.iloc[i].resume_bline

resume = resume_generator(258)

In [775]:
next(resume)

(13, ['amal.allouch.aa@gmail.com', 'contact #: 647-234-9968', ''])

In [774]:
# for i in range(1,253):
#     next(resume)

In [1049]:
# List of resumes with problems phase1
resume_load_problems1 = [13,16,28,40,49,57,59,64,71,72,84,85,92,94,97,118,125,130,132,134,140,163,172,179,182,188,193,194,195,209,213,219,223,246]
len(resume_load_problems1)

34

In [1050]:
# Frame of resumes with problems
df_resume_w_problems=df1[df1.index.isin(resume_load_problems1)]
df_resume_w_problems

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code,store,language
13,"Allouch, Amal - WE 531 - N58",docx,"Allouch, Amal",WE 531,N58,"[amal.allouch.aa@gmail.com, contact #: 647-234...",amal.allouch.aa@gmail.com contact #: 647-234-9...,1,"Allouch, Amal",N58,WE 531,English
16,"Ansari Rad, Naser - WW 850",docx,"Ansari Rad, Naser",WW 850,NO_UID,"[, , , , , , \t, , , , , , , , ]",\t,1,"Ansari Rad, Naser",N01,WW 850,English
28,"Balche, Naji - TB 441 - N2I",docx,"Balche, Naji",TB 441,N2I,"[NAJI BALCHE, 81 ELVIRA CRESCENT L...",NAJI BALCHE 81 ELVIRA CRESCENT LON...,1,"Balche, Naji",N2I,TB 441,English
40,"Brar, Surat - WW 148 - MQG",docx,"Brar, Surat",WW 148,MQG,[],,1,"Brar, Surat",MQG,WW 148,English
49,"Chaudhari, Dharmik - TB 422 - N12",docx,"Chaudhari, Dharmik",TB 422,N12,[],,1,"Chaudhari, Dharmik",N12,TB 422,English
57,"Chung, Young - WE 535 - MRI",docx,"Chung, Young",WE 535,MRI,"[, ]",,1,"Chung, Young",MRI,WE 535,English
59,"Cunningham, Benjamin James - WW 357",docx,"Cunningham, Benjamin James",WW 357,NO_UID,"[Experience, Ben Cunningham, Professional Refe...",Experience Ben Cunningham Professional Referen...,1,"Cunningham, Benjamin James",MYI,WW 357,English
64,"Dor-Traynor, Corey - WW 330 - MWK",docx,"Dor-Traynor, Corey",WW 330,MWK,"[BEST BUY CANADA, thornlea secondary school, ]",BEST BUY CANADA thornlea secondary school,1,"Dor-Traynor, Corey",MWK,WW 330,English
71,"Elbajegni, Omar - WW 295 - N1N",docx,"Elbajegni, Omar",WW 295,N1N,"[, ]",,1,"Elbajegni, Omar",N1N,WW 295,English
72,"Elejel, Ali - WE 530 - N67",docx,"Elejel, Ali",WE 530,N67,"[, , , ]",,1,"Elejel, Ali",N67,WE 530,English
84,"Gill, Karan - WE 156 - N2E",docx,"Gill, Karan",WE 156,N2E,"[, Volunteered at Annual Nagar Kirtan Parade -...",Volunteered at Annual Nagar Kirtan Parade - ...,1,"Gill, Karan",N2E,WE 156,English
85,"Gilles, Luigi - WW 365",docx,"Gilles, Luigi",WW 365,NO_UID,"[Luigi Gilles, luigi20091@live.com | | ...",Luigi Gilles luigi20091@live.com | | H:...,1,"Gilles, Luigi",MY7,WW 365,English
92,"Hamatto, Safia - WW 389 - MQI",docx,"Hamatto, Safia",WW 389,MQI,"[Objective, Experience, , ...",Objective Experience ...,1,"Hamatto, Safia",MQI,WW 389,English
94,"Harrouk, Toufik - TB 102 - N2O",docx,"Harrouk, Toufik",TB 102,N2O,[],,1,"Harrouk, Toufik",N2O,TB 102,English
97,"Hayes, James - WW 299 - MWT",docx,"Hayes, James",WW 299,MWT,"[James Hayes, , ]",James Hayes,1,"Hayes, James",MWT,WW 299,English
118,"Khanafer, Yarah - WE 530 - N3V",docx,"Khanafer, Yarah",WE 530,N3V,"[, , , , , , ]",,1,"Khanafer, Yarah",N3V,WE 530,English
125,"Laqui, Marley - WE 255",docx,"Laqui, Marley",WE 255,NO_UID,[],,1,"Laqui, Marley",N9W,WE 255,English
130,"LeBlanc, Jean-Michel - WE 551",docx,"LeBlanc, Jean-Michel",WE 551,NO_UID,"[, ]",,1,"LeBlanc, Jean-Michel",MYF,WE 551,English
132,"Li, Mingxiao - WW 280",docx,"Li, Mingxiao",WW 280,NO_UID,"[, ]",,1,"Li, Mingxiao",ND5,WW 280,English
134,"Luthra, Kunal - TB 422 - MW9",docx,"Luthra, Kunal",TB 422,MW9,"[, , ]",\n,1,"Luthra, Kunal",MW9,TB 422,English
140,"Mavi, Sumeet - TB 469",docx,"Mavi, Sumeet",TB 469,NO_UID,[ ...,...,1,"Mavi, Sumeet",N08,TB 469,English
163,"Nurse, Brady - WW 296 - MU6",docx,"Nurse, Brady",WW 296,MU6,"[, I’ve been involved in competitive fitness f...",I’ve been involved in competitive fitness for...,1,"Nurse, Brady",MU6,WW 296,English
172,"Pham, Danny - WE 547 - N9L",docx,"Pham, Danny",WE 547,N9L,"[, , , , , , ]",,1,"Pham, Danny",N9L,WE 547,English
179,"Rahmani, Amirali - WW 143 - N1I",docx,"Rahmani, Amirali",WW 143,N1I,"[Amirali Rahmani, 1504-945 Marine Drive | West...",Amirali Rahmani 1504-945 Marine Drive | West V...,1,"Rahmani, Amirali",N1I,WW 143,English
182,"Rawding, Kyle - TB 468 - MQO",docx,"Rawding, Kyle",TB 468,MQO,"[ , , , ]",\n,1,"Rawding, Kyle",MQO,TB 468,English
188,"Robinson, Kyle - WW 136",docx,"Robinson, Kyle",WW 136,NO_UID,"[Kyle robinson, , References, ]",Kyle robinson References,1,"Robinson, Kyle",MXI,WW 136,English
193,"Saharan, Divya - WW 366 - NDU",docx,"Saharan, Divya",WW 366,NDU,"[ DIVYA SAHARAN, ]",DIVYA SAHARAN,1,"Saharan, Divya",NDU,WW 366,English
194,"Sahilu, Zadig - WW 365 - MSW",docx,"Sahilu, Zadig",WW 365,MSW,"[, ]",,1,"Sahilu, Zadig",MSW,WW 365,English
195,"Saleem, Muhammad Junaid - TB 420 - N17",docx,"Saleem, Muhammad Junaid",TB 420,N17,[],,1,"Saleem, Muhammad Junaid",N17,TB 420,English
209,"Siddik, Mohammad Yashar - TB 283",docx,"Siddik, Mohammad Yashar",TB 283,NO_UID,"[, MOHAMMAD SIDDIK, ]",MOHAMMAD SIDDIK,1,"Siddik, Mohammad Yashar",MO9,TB 283,English
213,"Singh, Jagdeep - TB 434 - N0U",docx,"Singh, Jagdeep",TB 434,N0U,"[, Debugging and handling various coding langu...",Debugging and handling various coding languag...,1,"Singh, Jagdeep",N0U,TB 434,English
219,"Singh, Rupinderpal - WW 137 - N54",docx,"Singh, Rupinderpal",WW 137,N54,"[, , Technical skills, , ]",Technical skills,1,"Singh, Rupinderpal",N54,WW 137,English
223,"Spencer, Nathanael - WE 252 - MRZ",docx,"Spencer, Nathanael",WE 252,MRZ,"[, , , , , ]",,1,"Spencer, Nathanael",MRZ,WE 252,English
246,"Wong, Randy - WE 51 - N6I",docx,"Wong, Randy",WE 51,N6I,"[Randy Wong, , ]",Randy Wong,1,"Wong, Randy",N6I,WE 51,English

In [1026]:
# Export as csv file to the output folder
df_resume_w_problems.to_csv("../../data/output/docx_english_resume_w_problems.csv")

In [1051]:
# Frame of resumes without problems
df_clean = df1.loc[set(df1.index) - set(resume_load_problems1)]

In [1052]:
# Check CV is OK
df_clean#.iloc[16].resume_bline

,file_name,file_type,meta_e_name,meta_s_id,meta_u_id,resume_bline,resume_text,f_name_match,employee_name,employee_code,store,language
0,"Abbasi, Samiee Z - WW 374 - N42",docx,"Abbasi, Samiee Z",WW 374,N42,"[Samiee Zahid Abbasi, 61 Muscat Crescent Ajax,...","Samiee Zahid Abbasi 61 Muscat Crescent Ajax, O...",1,"Abbasi, Samiee Z",N42,WW 374,English
1,"Abrams, James - WW 851 - MZV",docx,"Abrams, James",WW 851,MZV,"[Michael Abrams , 5214 Gerrish Street, Apt 221...","Michael Abrams 5214 Gerrish Street, Apt 221 C...",1,"Abrams, James",MZV,WW 851,English
2,"Abrum, Nabil - WE 540 - N7R",docx,"Abrum, Nabil",WE 540,N7R,"[Nabil Abrum, 1042B Beryl Private, Ottawa, ON ...","Nabil Abrum 1042B Beryl Private, Ottawa, ON K1...",1,"Abrum, Nabil",N7R,WE 540,English
3,"Ahammed, Kawser - WW 284",docx,"Ahammed, Kawser",WW 284,NO_UID,"[Kawser Ahammed, 414-1225 Moss Avenue, Saskato...","Kawser Ahammed 414-1225 Moss Avenue, Saskatoon...",1,"Ahammed, Kawser",NBQ,WW 284,English
4,"Ahmad, Waqar - WE 162 - MU9",docx,"Ahmad, Waqar",WE 162,MU9,"[Waqar Ahmad, 158 Fleetwood Crescent, Brampton...","Waqar Ahmad 158 Fleetwood Crescent, Brampton, ...",1,"Ahmad, Waqar",MU9,WE 162,English
...,...,...,...,...,...,...,...,...,...,...,...,...
253,"Yang, Shih Min - WW 148 - N8A",docx,"Yang, Shih Min",WW 148,N8A,"[Samson Yang, , ------------------------------...",Samson Yang ---------------------------------...,1,"Yang, Shih Min",N8A,WW 148,English
254,"Yen, Shen - WW 145 - N0M",docx,"Yen, Shen",WW 145,N0M,"[Joey Yen, Richmond, BC, Canada (778)-323-...","Joey Yen Richmond, BC, Canada (778)-323-05...",1,"Yen, Shen",N0M,WW 145,English
255,"Yim, Eddy - TB 417 - N1M",docx,"Yim, Eddy",TB 417,N1M,[ ...,...,1,"Yim, Eddy",N1M,TB 417,English
256,"Zaveree, Shehzad - TB 415 - NE0",docx,"Zaveree, Shehzad",TB 415,NE0,[SHEHZAD ZAVEREE ...,SHEHZAD ZAVEREE ...,1,"Zaveree, Shehzad",NE0,TB 415,English
257,"Zhu, WeiWei - WW353 - MQF",docx,"Zhu, WeiWei",WW353,MQF,"[Weiwei Zhu, \tHome Address:\t\t\t\t , 160 cha...",Weiwei Zhu \tHome Address:\t\t\t\t 160 chapel...,1,"Zhu, WeiWei",MQF,WW 353,English

In [1053]:
# Export as csv file to the output folder
df_clean.to_csv("../../data/output/docx_english_resume_phase1_224.csv")

In [797]:
def resume_generator2(n):
    for i in range(0,n):
        yield i, df_clean.iloc[i].resume_bline

resume2 = resume_generator2(223)

In [1021]:
next(resume2)

StopIteration:

### Doing pd.merge way adds 2 more rows (Duplicates?)

In [324]:
df1['employee_name'] = df1['e_name']
df_merged = (pd.merge(df1, df2, how="left", on=["employee_name"])).drop(columns=["employee_name",
                                                                                "employee_code",
                                                                                "store",
                                                                                "ADP ID",
                                                                                "District",
                                                                                "Job Title Description",
                                                                                "Hire Date"])

df1=df1.drop(columns=["employee_name"])
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260 entries, 0 to 259
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   file_name     260 non-null    object
 1   file_type     260 non-null    object
 2   meta_e_name   260 non-null    object
 3   meta_s_id     260 non-null    object
 4   meta_u_id     260 non-null    object
 5   resume        260 non-null    object
 6   f_name_match  260 non-null    int32
 7   e_name        260 non-null    object
 8   e_code        259 non-null    object
 9   s_code        260 non-null    object
 10  language_x    260 non-null    object
 11  language_y    260 non-null    object
dtypes: int32(1), object(11)
memory usage: 25.4+ KB

In [272]:
df1=df1.drop(columns=["u_id"])